---
title: "01: Desempenho agronômico do linho em diferentes épocas de semeadura"
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Pacotes

To reproduce the examples of this material, the R packages the following packages are needed.

```{r warning=FALSE, message=FALSE}
library(rio)
library(tidyverse)
library(AgroR)
library(metan)

```


# Dados
```{r}
df_p <-
  import("data/data_parcelas.csv")
```


# Análise de variância
## Rendimento de grãos
```{r}
modrg <- with(df_p,
            PSUBDBC(epoca, cultivar, bloco, rgha,
                    xlab = "Épocas de semeadura"))

rg <- 
modrg$graph1 +
  labs(x = "Épocas de semeadura",
       y = expression(Rendimento~de~grãos~(kg~ha^{-1})))
```

## Massa de mil grãos
```{r}
modmmg <- with(df_p,
            PSUBDBC(epoca, cultivar, bloco, mmg))
mmg <- 
  modmmg$graph1 +
  labs(x = "Épocas de semeadura",
       y = "Massa de mil grãos (g)")

arrange_ggplot(rg, mmg,
               tag_levels = "a")
ggsave("figs/rg_mmg.jpg",
       width = 8,
       height = 4)
```


## Número de cápsulas
```{r}
modnc <- with(df_p,
            PSUBDBC(epoca, cultivar, bloco, nc))
pnce <-
  modnc$graph1 +
  labs(x = "Épocas de semeadura",
       y = "Número de cápsulas")

pncc <-
  modnc$graph2 +
  labs(x = "Cultivares",
       y = "Número de cápsulas")

arrange_ggplot(pnce, pncc, widths = c(0.75, 0.25), tag_levels = "a")

ggsave("figs/nc.jpg",
       width = 8,
       height = 4)
```

# Correlação
```{r}
corr_coef(df_p, rgha, mmg, nc) |> 
  network_plot(legend_position = "bottom")

ggsave("figs/corr_epocas.jpg",
       width = 10,
       height = 3)
```


# Section info
```{r}
sessionInfo()
```

