project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

theme:
  light: flatly
  dark: darkly
website:
  search:
    location: sidebar
  title: "67 RBras e 22 SEAGRO"
  page-footer:
    border: true
    background: light
    left: "Núcleo de Estudos e Pesquisas em Experimentação e Melhoramento Vegetal - NEPEM"
    right: "FIT/CCA/UFSC "
  page-navigation: true
  navbar:
    background: "#0759e8"
    # foreground: dark
    search: true
    left:
      - text: "About"
        file: 00_about.qmd
        icon: fa fa-home


    right:
      - icon: "fab fa-researchgate fa"
        href: https://www.researchgate.net/profile/Tiago_Olivoto
      - icon: bi bi-github
        href: https://github.com/TiagoOlivoto/pliman
      - icon: bi bi-twitter
        href: https://twitter.com/tolivoto
      - icon: "fab fa-mendeley fa"
        href: https://www.mendeley.com/profiles/tiago-olivoto/


  sidebar:
    - title: "Contents"
      style: "docked"
      background: light
      contents:
        - 01_medias.qmd
        - 02_selecao_direta_indireta.qmd
        - 03_indice_selecao.qmd
        - 04_modelo_crescimento.qmd
        - 05_trilha.qmd
        - 06_canonica.qmd
        - 07_diversidade.qmd
        - 08_mgidi_fai.qmd
        - 09_dgci.qmd
        - 10_pred_af.qmd

format:
  html: 
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
    theme:
       light: journal
       dark: darkly
    toc: true
    toc-title: "In this page"
    number-sections: true
    number-depth: 3
    smooth-scroll: true
    code-fold: false
    code-tools: true
    code-block-bg: "#f5f2f2"
    highlight-style: tango
    code-block-border-left: "#31BAE9"
    code-link: true
    


execute:
  collapse: true
fig-responsive: true
fig-align: center
